
package ucss_calculator;

import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import com.sun.prism.Image;
import java.awt.Color;
import java.awt.*;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.*;

public class F_Calculadora extends javax.swing.JFrame {

    public class Imagen extends javax.swing.JPanel{
        String foto;
        public Imagen(int x,int y,String g){
            this.setSize(x, y);
            foto=g;
        }
        public void paint(Graphics grafico){
            Dimension tamaño=getSize();
            ImageIcon img=new ImageIcon(getClass().getResource("/media/"+foto));
            grafico.drawImage(img.getImage(), 0, 0, tamaño.width,tamaño.height,null);
            setOpaque(false);
            super.paintComponent(grafico);
        }
    }
    /**
     * Creates new form F_Calculadora
     */
    int c=1;
    char op='s';
    ArrayList<JTextField> n = new ArrayList<JTextField>();
    public F_Calculadora() {
        initComponents();
        cargaImagen();
        llenarArray();
        txtNumCont.setText(c+"");
        txtNumCont.setEditable(false);
        txtContinua2.setEnabled(false);
        txtContinua3.setEnabled(false);
        txtContinua4.setEnabled(false);
        txtContinua5.setEnabled(false);
        txtContinua6.setEnabled(false);
        txtContinua7.setEnabled(false);
        txtContinua8.setEnabled(false);
        
    }
    @Override
    public java.awt.Image getIconImage() {
        java.awt.Image retValue =Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("media/icono.png"));
        return retValue; //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelPonderado = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        txtContinua = new javax.swing.JTextField();
        txtEP1 = new javax.swing.JTextField();
        txtEP2 = new javax.swing.JTextField();
        txtEP3 = new javax.swing.JTextField();
        txtExF = new javax.swing.JTextField();
        txtPromFinal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnPromedio = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        lblRes = new javax.swing.JLabel();
        PanelContinuas = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtContinua1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtContinua2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtContinua3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtContinua4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtContinua5 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtContinua6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtContinua7 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtContinua8 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        btnMasC = new javax.swing.JButton();
        btnMenosC = new javax.swing.JButton();
        txtNumCont = new javax.swing.JTextField();
        btnCalCont = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        panelCree = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelJava = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UCSS Calculator");
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(400, 260));
        setMinimumSize(new java.awt.Dimension(400, 260));
        setSize(new java.awt.Dimension(400, 260));
        getContentPane().setLayout(null);

        PanelPonderado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelPonderado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCalcular.setFont(new java.awt.Font("Webdings", 0, 14)); // NOI18N
        btnCalcular.setText("");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        PanelPonderado.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, 30));

        txtContinua.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContinua.setName(""); // NOI18N
        txtContinua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContinuaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContinuaKeyTyped(evt);
            }
        });
        PanelPonderado.add(txtContinua, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, 35, -1));

        txtEP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEP1.setName(""); // NOI18N
        txtEP1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEP1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEP1KeyTyped(evt);
            }
        });
        PanelPonderado.add(txtEP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 35, -1));

        txtEP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEP2.setName(""); // NOI18N
        txtEP2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEP2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEP2KeyTyped(evt);
            }
        });
        PanelPonderado.add(txtEP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 35, -1));

        txtEP3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEP3.setName(""); // NOI18N
        txtEP3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEP3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEP3KeyTyped(evt);
            }
        });
        PanelPonderado.add(txtEP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 35, -1));

        txtExF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtExF.setName(""); // NOI18N
        txtExF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtExFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExFKeyTyped(evt);
            }
        });
        PanelPonderado.add(txtExF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 35, -1));

        txtPromFinal.setEditable(false);
        txtPromFinal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPromFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPromFinal.setName(""); // NOI18N
        PanelPonderado.add(txtPromFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 40, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EC");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelPonderado.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 35, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("EP 1");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        PanelPonderado.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 35, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("EP 2");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        PanelPonderado.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 35, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("EP 3");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        PanelPonderado.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 35, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ex F");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        PanelPonderado.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 35, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("P F");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        PanelPonderado.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 35, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("20%");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        PanelPonderado.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 35, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("10%");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        PanelPonderado.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 35, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("20%");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        PanelPonderado.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 35, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("30%");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        PanelPonderado.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 35, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("20%");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        PanelPonderado.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 35, -1));

        jLabel13.setText("* Inserte aqui sus notas de examenes");
        PanelPonderado.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnPromedio.setFont(new java.awt.Font("Webdings", 0, 14)); // NOI18N
        btnPromedio.setForeground(new java.awt.Color(255, 191, 0));
        btnPromedio.setText("");
        btnPromedio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromedioActionPerformed(evt);
            }
        });
        PanelPonderado.add(btnPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, 30));

        lblMensaje.setFont(new java.awt.Font("Webdings", 0, 24)); // NOI18N
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelPonderado.add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 50, 40));

        lblRes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelPonderado.add(lblRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 110, 20));

        jTabbedPane1.addTab("Promedio", PanelPonderado);

        PanelContinuas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setText("* Ingrese aqui sus evaluaciones continuas");

        jLabel15.setText("Numero de Evaluaciones:");

        txtContinua1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContinua1.setToolTipText("");
        txtContinua1.setName(""); // NOI18N
        txtContinua1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContinua1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContinua1KeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("EC1");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtContinua2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContinua2.setName(""); // NOI18N
        txtContinua2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContinua2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContinua2KeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("EC2");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtContinua3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContinua3.setName(""); // NOI18N
        txtContinua3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContinua3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContinua3KeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("EC3");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtContinua4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContinua4.setName(""); // NOI18N
        txtContinua4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContinua4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContinua4KeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("EC4");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtContinua5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContinua5.setName(""); // NOI18N
        txtContinua5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContinua5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContinua5KeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("EC5");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtContinua6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContinua6.setName(""); // NOI18N
        txtContinua6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContinua6KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContinua6KeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("EC6");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtContinua7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContinua7.setName(""); // NOI18N
        txtContinua7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContinua7KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContinua7KeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("EC7");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtContinua8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContinua8.setName(""); // NOI18N
        txtContinua8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContinua8KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContinua8KeyTyped(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("EC8");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnMasC.setText("+");
        btnMasC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMasC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasCActionPerformed(evt);
            }
        });

        btnMenosC.setText("-");
        btnMenosC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenosC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosCActionPerformed(evt);
            }
        });

        txtNumCont.setEditable(false);

        btnCalCont.setText("⌂");
        btnCalCont.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalContActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelContinuasLayout = new javax.swing.GroupLayout(PanelContinuas);
        PanelContinuas.setLayout(PanelContinuasLayout);
        PanelContinuasLayout.setHorizontalGroup(
            PanelContinuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContinuasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelContinuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelContinuasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCalCont))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelContinuasLayout.createSequentialGroup()
                        .addGroup(PanelContinuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelContinuasLayout.createSequentialGroup()
                                .addGroup(PanelContinuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContinua1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelContinuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContinua2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelContinuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContinua3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelContinuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContinua4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelContinuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContinua5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelContinuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContinua6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelContinuasLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumCont, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PanelContinuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelContinuasLayout.createSequentialGroup()
                                .addComponent(btnMasC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMenosC))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelContinuasLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(PanelContinuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContinua7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelContinuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContinua8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PanelContinuasLayout.setVerticalGroup(
            PanelContinuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContinuasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelContinuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(btnMasC)
                    .addComponent(btnMenosC)
                    .addComponent(txtNumCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelContinuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelContinuasLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(4, 4, 4)
                        .addComponent(txtContinua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelContinuasLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(4, 4, 4)
                        .addComponent(txtContinua2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelContinuasLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(4, 4, 4)
                        .addComponent(txtContinua3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelContinuasLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(4, 4, 4)
                        .addComponent(txtContinua4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelContinuasLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(4, 4, 4)
                        .addComponent(txtContinua5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelContinuasLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(4, 4, 4)
                        .addComponent(txtContinua6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelContinuasLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(4, 4, 4)
                        .addComponent(txtContinua7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelContinuasLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(4, 4, 4)
                        .addComponent(txtContinua8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalCont)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ev. Continuas", null, PanelContinuas, "");

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 80, 380, 170);

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(400, 40));
        jPanel2.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Calculadora UCSS");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(20, 20, 159, 22);

        panelCree.setBackground(new java.awt.Color(0, 204, 255));
        panelCree.setMaximumSize(new java.awt.Dimension(400, 40));

        javax.swing.GroupLayout panelCreeLayout = new javax.swing.GroupLayout(panelCree);
        panelCree.setLayout(panelCreeLayout);
        panelCreeLayout.setHorizontalGroup(
            panelCreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelCreeLayout.setVerticalGroup(
            panelCreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(panelCree);
        panelCree.setBounds(290, 10, 100, 30);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("2013100403");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 10, 70, 14);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 410, 50);

        javax.swing.GroupLayout panelJavaLayout = new javax.swing.GroupLayout(panelJava);
        panelJava.setLayout(panelJavaLayout);
        panelJavaLayout.setHorizontalGroup(
            panelJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelJavaLayout.setVerticalGroup(
            panelJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(panelJava);
        panelJava.setBounds(350, 50, 40, 40);

        setSize(new java.awt.Dimension(416, 296));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void cargaImagen(){        
        Imagen img1 = new Imagen(100,30,"cree.png");      
        panelCree.add(img1);
        panelCree.repaint();
        Imagen img3 = new Imagen(40,40,"java.png");
        panelJava.add(img3);
        panelJava.repaint();
        
    }
    private void vacioP(){
        if("".equals(txtContinua.getText()) || Double.parseDouble(txtContinua.getText())>20 || Double.parseDouble(txtContinua.getText())<0){txtContinua.setText("0");}
        if("".equals(txtEP1.getText())|| Double.parseDouble(txtEP1.getText())>20 || Double.parseDouble(txtEP1.getText())<0){txtEP1.setText("0");}
        if("".equals(txtEP2.getText())|| Double.parseDouble(txtEP2.getText())>20 || Double.parseDouble(txtEP2.getText())<0){txtEP2.setText("0");}
        if("".equals(txtEP3.getText())|| Double.parseDouble(txtEP3.getText())>20 || Double.parseDouble(txtEP3.getText())<0){txtEP3.setText("0");}
        if("".equals(txtExF.getText())|| Double.parseDouble(txtExF.getText())>20 || Double.parseDouble(txtExF.getText())<0){txtExF.setText("0");}
    }
    private void vacioC(){
        if("".equals(txtContinua1.getText()) || Double.parseDouble(txtContinua1.getText())>20 || Double.parseDouble(txtContinua1.getText())<0){txtContinua1.setText("0");}
        if("".equals(txtContinua2.getText()) || Double.parseDouble(txtContinua2.getText())>20 || Double.parseDouble(txtContinua2.getText())<0){txtContinua2.setText("0");}
        if("".equals(txtContinua3.getText()) || Double.parseDouble(txtContinua3.getText())>20 || Double.parseDouble(txtContinua3.getText())<0){txtContinua3.setText("0");}
        if("".equals(txtContinua4.getText()) || Double.parseDouble(txtContinua4.getText())>20 || Double.parseDouble(txtContinua4.getText())<0){txtContinua4.setText("0");}
        if("".equals(txtContinua5.getText()) || Double.parseDouble(txtContinua5.getText())>20 || Double.parseDouble(txtContinua5.getText())<0){txtContinua5.setText("0");}
        if("".equals(txtContinua6.getText()) || Double.parseDouble(txtContinua6.getText())>20 || Double.parseDouble(txtContinua6.getText())<0){txtContinua6.setText("0");}
        if("".equals(txtContinua7.getText()) || Double.parseDouble(txtContinua7.getText())>20 || Double.parseDouble(txtContinua7.getText())<0){txtContinua7.setText("0");}
        if("".equals(txtContinua8.getText()) || Double.parseDouble(txtContinua8.getText())>20 || Double.parseDouble(txtContinua8.getText())<0){txtContinua8.setText("0");}
        
    }
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        vacioP();
        double cont,ep1,ep2,ep3,exf,prom;
        DecimalFormat dc = new DecimalFormat("#.00");
        String form;
        cont=Double.parseDouble(txtContinua.getText());
        ep1=Double.parseDouble(txtEP1.getText());
        ep2=Double.parseDouble(txtEP2.getText());
        ep3=Double.parseDouble(txtEP3.getText());
        exf=Double.parseDouble(txtExF.getText());
        prom=cont*0.2+ep1*0.1+ep2*0.2+ep3*0.2+exf*0.3;    
        txtPromFinal.setText(prom+"");
        form=dc.format(prom);
        form=form.replace(',', '.');
        txtPromFinal.setText(form);
        txtExF.setForeground(Color.BLACK); 
        formato_Prom('s');
    }//GEN-LAST:event_btnCalcularActionPerformed
private void formato_Prom(char opc){
String m="";
double p=Double.parseDouble(txtPromFinal.getText());
if(opc=='s'){
    lblMensaje.setForeground(Color.BLACK);
        lblRes.setForeground(Color.BLACK);
    if(p<10.5){
        txtPromFinal.setForeground(Color.RED);
        m="You Lose!";
        lblMensaje.setText("");
    }
    else{
        txtPromFinal.setForeground(Color.BLACK);
        m="You Win!";
        lblMensaje.setText("");
    }
}
else if(opc=='n'){
    txtExF.setForeground(Color.BLUE);
    txtPromFinal.setForeground(Color.GREEN);
    if(p>=10.5){
        m="You Win!!";
        lblMensaje.setText("");
        lblMensaje.setForeground(Color.yellow);
        lblRes.setForeground(Color.YELLOW);
    }
    else{
        m="You Lose!!";
        lblMensaje.setText("");
        lblMensaje.setForeground(Color.RED);
        lblRes.setForeground(Color.RED);
    }
}
    lblRes.setText(m);
    txtPromFinal.setText(p+"");
}
//llena el array n con todos los Texbox de la pestaña 'Continuas'
    private void llenarArray(){
    n.add(txtContinua1);
    n.add(txtContinua2);
    n.add(txtContinua3);
    n.add(txtContinua4);
    n.add(txtContinua5);
    n.add(txtContinua6);
    n.add(txtContinua7);
    n.add(txtContinua8);
}
    //cuenta los Texbox activados y suma su contenido
    private void continuas(int x){
    int y=0;
    while(y<8){
        if(y<x){
            n.get(y).setEnabled(true);
        }
        else{
            n.get(y).setEnabled(false);
        }
    y++;
    }
}
    private void promC(){
    int c=0;
    double p=0;
    for(int i=0;i<n.size();i++){
        if(n.get(i).isEnabled()){
            c=c+1;
            p=p+Double.parseDouble(n.get(i).getText());
        }
    }
    txtContinua.setText(""+p/c);
    }
    private void btnMasCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasCActionPerformed
        // TODO add your handling code here:
        if(c==8){c=8;}
        else{c=c+1;}
        txtNumCont.setText(c+"");
        continuas(c);
    }//GEN-LAST:event_btnMasCActionPerformed

    private void btnMenosCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosCActionPerformed
        // TODO add your handling code here:
        if(c==1){c=1;}
        else{c=c-1;}
        txtNumCont.setText(c+"");
        continuas(c);
    }//GEN-LAST:event_btnMenosCActionPerformed

    private void btnCalContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalContActionPerformed
        // TODO add your handling code here:
        vacioC();
        promC();
    }//GEN-LAST:event_btnCalContActionPerformed
    
    private void btnPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedioActionPerformed
        // TODO add your handling code here:
        vacioP(); 
        double co,ep1,ep2,ep3,exf,prom;
        double aux=0;
        co=Double.parseDouble(txtContinua.getText());
        ep1=Double.parseDouble(txtEP1.getText());
        ep2=Double.parseDouble(txtEP2.getText());
        ep3=Double.parseDouble(txtEP3.getText());
        exf=Double.parseDouble(txtExF.getText());
        DecimalFormat dc=new DecimalFormat("#.00");
        String form;
        prom=0;
        double x=exf;
        while(prom<10.5 && aux<=20){    
            x=aux;
            aux+=1;
            prom=co*0.2+ep1*0.1+ep2*0.2+ep3*0.2+x*0.3;
        }    
        txtExF.setText(x+"");
        form=dc.format(prom);
        form=form.replace(',', '.');
        this.txtPromFinal.setText(form);
        formato_Prom('n');
    }//GEN-LAST:event_btnPromedioActionPerformed
    private void mover1(java.awt.event.KeyEvent evt, JTextField t,int m){
        if(evt.getExtendedKeyCode()==10){
            if(t.getText().equals("")){  t.setText("0");}            
            switch (m) {
                case 0:
                    this.txtContinua.requestFocus();
                    break;
                case 1:
                    this.txtEP1.requestFocus();
                    break;
                case 2:
                    this.txtEP2.requestFocus();
                    break;
                case 3:
                    this.txtEP3.requestFocus();
                    break;
                case 4:
                    this.txtExF.requestFocus();
                    break;
                default:
                    break;
            }
        }
    }
    private void txtContinuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinuaKeyReleased
        mover1(evt,txtContinua,1);
    }//GEN-LAST:event_txtContinuaKeyReleased
    private void validar(java.awt.event.KeyEvent evt,String t){
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            evt.consume();
            JOptionPane.showMessageDialog(PanelContinuas,evt.getKeyChar()+" \nIngrese solo números");            
        }
        if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&t.contains(".")){
            evt.consume();
        }
    }
    private void txtContinuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinuaKeyTyped
        validar(evt,txtContinua.getText());
    }//GEN-LAST:event_txtContinuaKeyTyped

    private void txtEP1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEP1KeyTyped
        validar(evt,txtEP1.getText());       
    }//GEN-LAST:event_txtEP1KeyTyped

    private void txtEP2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEP2KeyTyped
        validar(evt,txtEP2.getText());
    }//GEN-LAST:event_txtEP2KeyTyped

    private void txtEP3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEP3KeyTyped
        validar(evt,txtEP3.getText());
    }//GEN-LAST:event_txtEP3KeyTyped

    private void txtExFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExFKeyTyped
        validar(evt,txtExF.getText());
    }//GEN-LAST:event_txtExFKeyTyped

    private void txtContinua1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinua1KeyTyped
        validar(evt,txtContinua1.getText());
    }//GEN-LAST:event_txtContinua1KeyTyped

    private void txtContinua2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinua2KeyTyped
        validar(evt,txtContinua2.getText());
    }//GEN-LAST:event_txtContinua2KeyTyped

    private void txtContinua3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinua3KeyTyped
        validar(evt,txtContinua3.getText());
    }//GEN-LAST:event_txtContinua3KeyTyped

    private void txtContinua4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinua4KeyTyped
        validar(evt,txtContinua4.getText());
    }//GEN-LAST:event_txtContinua4KeyTyped

    private void txtContinua5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinua5KeyTyped
        validar(evt,txtContinua5.getText());
    }//GEN-LAST:event_txtContinua5KeyTyped

    private void txtContinua6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinua6KeyTyped
        validar(evt,txtContinua6.getText());
    }//GEN-LAST:event_txtContinua6KeyTyped

    private void txtContinua7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinua7KeyTyped
        validar(evt,txtContinua7.getText());
    }//GEN-LAST:event_txtContinua7KeyTyped

    private void txtContinua8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinua8KeyTyped
        validar(evt,txtContinua8.getText());
    }//GEN-LAST:event_txtContinua8KeyTyped

    private void txtEP1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEP1KeyReleased
       mover1(evt,txtEP1,2);
    }//GEN-LAST:event_txtEP1KeyReleased

    private void txtEP2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEP2KeyReleased
        mover1(evt,txtEP2,3);
    }//GEN-LAST:event_txtEP2KeyReleased

    private void txtEP3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEP3KeyReleased
        mover1(evt,txtEP3,4);
    }//GEN-LAST:event_txtEP3KeyReleased

    private void txtExFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExFKeyReleased
        mover1(evt,txtExF,0);
    }//GEN-LAST:event_txtExFKeyReleased

    private void mover2(java.awt.event.KeyEvent evt,JTextField t,int m){
        if(evt.getExtendedKeyCode()==10){
            if(t.getText().equals("")){  t.setText("0");}            
            switch (m) {
                case 0:
                    this.txtContinua1.requestFocus();
                    break;
                case 1:
                    this.txtContinua2.requestFocus();
                    break;
                case 2:
                    this.txtContinua3.requestFocus();
                    break;
                case 3:
                    this.txtContinua4.requestFocus();
                    break;
                case 4:
                    this.txtContinua5.requestFocus();
                    break;
                case 5:
                    this.txtContinua6.requestFocus();
                    break;
                case 6:
                    this.txtContinua7.requestFocus();
                    break;
                case 7:
                    this.txtContinua8.requestFocus();
                    break;
                default:
                    break;
            }
        }
    }
    private void txtContinua1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinua1KeyReleased
        mover2(evt,txtContinua1,1);
    }//GEN-LAST:event_txtContinua1KeyReleased

    private void txtContinua2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinua2KeyReleased
        mover2(evt,txtContinua2,2);
    }//GEN-LAST:event_txtContinua2KeyReleased

    private void txtContinua3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinua3KeyReleased
        mover2(evt,txtContinua3,3);
    }//GEN-LAST:event_txtContinua3KeyReleased

    private void txtContinua4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinua4KeyReleased
        mover2(evt,txtContinua4,4);
    }//GEN-LAST:event_txtContinua4KeyReleased

    private void txtContinua5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinua5KeyReleased
        mover2(evt,txtContinua5,5);
    }//GEN-LAST:event_txtContinua5KeyReleased

    private void txtContinua6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinua6KeyReleased
        mover2(evt,txtContinua6,6);
    }//GEN-LAST:event_txtContinua6KeyReleased

    private void txtContinua7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinua7KeyReleased
        mover2(evt,txtContinua7,7);
    }//GEN-LAST:event_txtContinua7KeyReleased

    private void txtContinua8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContinua8KeyReleased
        mover2(evt,txtContinua8,0);
    }//GEN-LAST:event_txtContinua8KeyReleased
     /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                // UIManager cambia el aspecto tradicional del formulario
                try {
                    UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(F_Calculadora.class.getName()).log(Level.SEVERE, null, ex);
                }
                new F_Calculadora().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContinuas;
    private javax.swing.JPanel PanelPonderado;
    private javax.swing.JButton btnCalCont;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnMasC;
    private javax.swing.JButton btnMenosC;
    private javax.swing.JButton btnPromedio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblRes;
    private javax.swing.JPanel panelCree;
    private javax.swing.JPanel panelJava;
    private javax.swing.JTextField txtContinua;
    private javax.swing.JTextField txtContinua1;
    private javax.swing.JTextField txtContinua2;
    private javax.swing.JTextField txtContinua3;
    private javax.swing.JTextField txtContinua4;
    private javax.swing.JTextField txtContinua5;
    private javax.swing.JTextField txtContinua6;
    private javax.swing.JTextField txtContinua7;
    private javax.swing.JTextField txtContinua8;
    private javax.swing.JTextField txtEP1;
    private javax.swing.JTextField txtEP2;
    private javax.swing.JTextField txtEP3;
    private javax.swing.JTextField txtExF;
    private javax.swing.JTextField txtNumCont;
    private javax.swing.JTextField txtPromFinal;
    // End of variables declaration//GEN-END:variables
}
